### ISSUE TITLE
Milestone 4 - June 11 - Overview

### ISSUE THREAD

**Issue by jecluis** [aquarist-labs/aquarium#500]
### Dashboard
- [x] Add Capacity (i.e., real usage) #486 
- [x] Rename "Capacity" to "Allocated" #487 #525 
- [ ] Health message displayed on hover?
- [ ] Backend support for what is required
* ~Show time series delivered by Ceph itself (not from external source, e.g. Prometheus)~  #488  (moved to M5)
### Install Wizard
- [x] Devices config step #509 

## Testing improvements
- [x] All PRs need unit tests #460 
- [ ] Functional tests to stress the API (against a running cluster)
    - [x] Test battery #499 
    - [ ] API coverage
