### ISSUE TITLE
system disk support

### ISSUE THREAD

**Issue by jecluis** [aquarist-labs/aquarium#543]
- [x] create systemdisk on deployment of joining node (#541)
- [x] have disks + deployment step when extending new cluster (#540)
- [x] dissociate join from deployment for 2+ nodes (#539)
- [x] system disk mount on boot (#538) PR #548

**Comment by jecluis** [comment]
considering done as all tasks have either been achieved or rejected.
